# Generated by Django 2.1.4 on 2018-12-21 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 21, 12, 49, 8, 248549)),
        ),
    ]
