# Generated by Django 2.1.3 on 2019-01-13 16:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0018_auto_20190113_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pre_time',
            field=models.FloatField(default=1547397094.0284529),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 13, 16, 31, 34, 28426, tzinfo=utc)),
        ),
    ]
