# Generated by Django 2.1.4 on 2018-12-22 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('picture', models.ImageField(upload_to='profile-pictures/')),
                ('interests', models.TextField()),
                ('github', models.CharField(max_length=100)),
                ('linkedIn', models.CharField(max_length=100)),
                ('is_bom', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
