# Generated by Django 2.1.4 on 2018-12-23 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181222_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(140)]),
        ),
    ]
