# Generated by Django 2.1.4 on 2018-12-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181223_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='/defaults/default.png', upload_to='profile-pictures/'),
        ),
    ]
