# Generated by Django 2.1.4 on 2018-12-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181223_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='/defaults/defaul.png', upload_to='profile-pictures/'),
        ),
    ]
