# Generated by Django 2.1.4 on 2018-12-18 09:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 12, 18, 9, 37, 30, 478414))),
                ('main_image', models.ImageField(upload_to='blog-images/')),
                ('body', models.TextField()),
                ('likes', models.IntegerField(default=1)),
                ('comments', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
