# Generated by Django 2.1.3 on 2018-12-20 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181220_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='likers',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 12, 34, 53, 400364)),
        ),
    ]
