# Generated by Django 2.1.4 on 2018-12-22 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20181222_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 20, 24, 4, 857277)),
        ),
    ]
