# Generated by Django 2.1.4 on 2018-12-22 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20181222_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_read',
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 20, 24, 35, 510574)),
        ),
    ]
