# Generated by Django 2.1.4 on 2018-12-23 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20181223_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pre_time',
            field=models.FloatField(default=1545563578.68399),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 11, 12, 58, 683905, tzinfo=utc)),
        ),
    ]
