# Generated by Django 2.1.4 on 2018-12-27 05:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20181227_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(default='/defaults/default_blog_image.jpg', upload_to='blog-images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pre_time',
            field=models.FloatField(default=1545888000.1541243),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 5, 20, 0, 154038, tzinfo=utc)),
        ),
    ]
