# Generated by Django 2.1.3 on 2019-01-13 08:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20181227_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pre_time',
            field=models.FloatField(default=1547369682.548991),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 13, 8, 54, 42, 548898, tzinfo=utc)),
        ),
    ]
