# Generated by Django 2.1.4 on 2018-12-28 16:51

import ckeditor.fields
import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20181227_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, validators=[django.core.validators.MinLengthValidator(30)]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pre_time',
            field=models.FloatField(default=1546015892.0641713),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 28, 16, 51, 32, 64074, tzinfo=utc)),
        ),
    ]
