# Generated by Django 2.1.4 on 2018-12-28 17:04

import ckeditor_uploader.fields
import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20181228_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, validators=[django.core.validators.MinLengthValidator(30)]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pre_time',
            field=models.FloatField(default=1546016667.4704819),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 28, 17, 4, 27, 470378, tzinfo=utc)),
        ),
    ]
