# Generated by Django 2.1.3 on 2019-01-13 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20190113_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='pre_time',
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 13, 16, 34, 32, 400681, tzinfo=utc)),
        ),
    ]
