# Generated by Django 2.1.3 on 2018-12-20 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='goal',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 16, 40, 45, 424742)),
        ),
    ]
