# Generated by Django 2.1.3 on 2019-01-13 16:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='goal',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 13, 16, 31, 34, 29307, tzinfo=utc)),
        ),
    ]
