# Generated by Django 2.1.3 on 2019-01-13 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0002_auto_20190113_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 13, 16, 34, 32, 400019, tzinfo=utc)),
        ),
    ]
