# Generated by Django 2.1.4 on 2018-12-22 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0004_auto_20181221_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 22, 9, 7, 6, 214078)),
        ),
    ]
