# Generated by Django 2.1.4 on 2018-12-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0011_auto_20181223_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='time',
            field=models.FloatField(default=1545551624.452631),
        ),
    ]
