# Generated by Django 2.1.4 on 2018-12-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0012_auto_20181223_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='time',
            field=models.FloatField(default=1545557925.0955665),
        ),
    ]
