# Generated by Django 2.1.4 on 2018-12-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0013_auto_20181223_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='time',
            field=models.FloatField(default=1545563578.6832662),
        ),
    ]
