# Generated by Django 2.1.4 on 2018-12-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0015_auto_20181227_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='time',
            field=models.FloatField(default=1545888000.1533778),
        ),
    ]
