# Generated by Django 2.1.4 on 2018-12-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0016_auto_20181227_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='time',
            field=models.FloatField(default=1546015892.0615964),
        ),
    ]
