# Generated by Django 2.1.3 on 2019-01-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0018_auto_20181228_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='time',
            field=models.FloatField(default=1547369682.5482492),
        ),
    ]
