# Generated by Django 2.1.3 on 2018-12-20 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog_comment',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_writer',
            new_name='writer',
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 20, 14, 36, 47, 965790)),
        ),
    ]
