# Generated by Django 2.1.4 on 2018-12-23 07:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0013_auto_20181223_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pre_time',
            field=models.FloatField(default=1545551624.4539385),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 23, 7, 53, 44, 453920, tzinfo=utc)),
        ),
    ]
