# Generated by Django 2.1.4 on 2018-12-27 05:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0017_auto_20181227_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pre_time',
            field=models.FloatField(default=1545888000.1546962),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 27, 5, 20, 0, 154678, tzinfo=utc)),
        ),
    ]
