# Generated by Django 2.1.3 on 2019-01-13 16:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0022_auto_20190113_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pre_time',
            field=models.FloatField(default=1547397094.0311906),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 13, 16, 31, 34, 31172, tzinfo=utc)),
        ),
    ]
