# Generated by Django 2.1.3 on 2019-01-13 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0023_auto_20190113_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pre_time',
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 13, 16, 34, 32, 401267, tzinfo=utc)),
        ),
    ]
