# Generated by Django 2.1.3 on 2019-01-13 16:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0024_auto_20190113_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 13, 16, 49, 50, 406785, tzinfo=utc)),
        ),
    ]
